### ISSUE TITLE
Spamfilter inherit not shown

### ISSUE THREAD

**Issue by thompol** [w2c/ispconfig3_roundcube#102]
If you don't select a spamfilter for a mailbox it will inherit from the spamfilter that's selected for the domain (currently ISPC calls this "- Not enabled -" but this will probably be changed, see https://git.ispconfig.org/ispconfig/ispconfig3/issues/4277 milestone 3.2). But when you view the spamfilter settings through Roundcube (with the ispconfig3_spamfilter plugin) the spamfilter that's shown is the one that is first in the list, and not the "- Not enabled -" (which as said will change). You can't pick "- Not enabled - " from Roundcube either. This should be possible for the end user to do.

**Comment by Churro** [comment]
Thanks for the suggestion. However, there is not much we can (or will) do about that. Our plugin retrieves the list of possible policies [directly](https://github.com/w2c/ispconfig3_roundcube/blob/master/ispconfig3_spam/ispconfig3_spam.php#L144) from ISPConfig and does not rely on a hardcoded list. As soon as policies are added, modified / renamed, deleted, these changes are immediately reflected in Roundcube.

**Comment by thompol** [comment]
ISPConfig adds the - not enabled - option to the list. Imo this plugin should aswell, because it's a option that a lot of users will want to use. If a user is inheriting the domain policy, they don't see that in Roundcube, which is confusing.

**Comment by jnorell** [comment]
> If a user is inheriting the domain policy, they don't see that in Roundcube, which is confusing.

Also, a user cannot tell via the roundcube interface what the domain's policy is to know what to choose if they eg. just want to enable 'move to junk' without changing their current policy.

FWIW, I think there was a recent change in ISPConfig (possibly in 3.2.4 release?) where users who have "Inherit domain policy" set will actually have a spamfilter_users entry created for them, so the behavior seen by the plugin when testing may depend on the version of ISPConfig in use.  The solution/suggestion in this issue (ie. add something like a "Inherit Domain Policy" option to the select list) would work for any ISPConfig version.
