### ISSUE TITLE
No save button in Elastic skin (mobile devices)

### ISSUE THREAD

**Issue by dar-ek** [w2c/ispconfig3_roundcube#103]
Hi. I noticed that there is no button SAVE in Elastic skin, but only on mobile devices.

Roundcubemail 1.4.3

**Comment by Churro** [comment]
Hi,

I can confirm the bug. It doesn't only affect our plugins but basically any RC addon that implements the Elastic skin and renders pages using iFrames, e.g., `enigma` and `managesieve`.

Obviously, it seems to be a race condition: The longer it takes to load the page, the more likely it is to see a Save button. For instance, if you monitor script execution in the browser console, the induced delay was enough to show the Save button in ~50% of tries. 

I suspect the whole thing is related to the function `is_framed()` in https://github.com/roundcube/roundcubemail/blob/master/program/js/app.js#L1651,
so nothing we could fix within this project...
