### ISSUE TITLE
User/from shows loginuser@localhost

### ISSUE THREAD

**Issue by TonyGravagno** [w2c/ispconfig3_roundcube#110]
An ISPConfig Mailbox exists for user admin@foodomain.tld, with name "Administrator".
The Login is set to "fooadmin".
Login to Roundcube is successful as user "fooadmin".
But above the folder list the email address displays as fooadmin@localhost.

Settings > Identities shows Display Name "fooadmin" with Email "fooadmin@localhost".

Settings > Account > General shows username "fooadmin", server "localhost" and default sender "fooadmin <fooadmin@localhost>".

The Linked email addresses are all correct, except for "admin@foodomain.tld" which is shown as a Linked address, where I'd expect it to be the primary/general.

If I compose a new post, only that incorrect name/address is shown, and there are no linked accounts listed, though here I'd expect all of the linked addresses to be shown as alternative From addresses - Send-As is checked in all Email Aliases, and the addresses are Active.

**Comment by thompol** [comment]
I think this is a issue that only exists when using custom login names.

**Comment by TonyGravagno** [comment]
I'll see what happens with using a mailbox user@domain. If this is the issue I'd like to try to fix/enhance it. I prefer using a custom login. If an address gets spam-compromised it can be disposed at some point, and replaced with a new address under the same user login.

**Comment by thompol** [comment]
I can see the use of that though I think improving your spamfilter is a better idea for most users ;)

For identities, it is Roundcube behaviour and not from this plugin.

**Comment by TonyGravagno** [comment]
Roundcube is now set to accept the full email address for login. It does authenticate against ISPConfig.
Yes, above the folder list the email address now displays the correct admin@foodomain.tld.
