### ISSUE TITLE
Launch Roundcube from ISPConfig link, doesn't force login

### ISSUE THREAD

**Issue by TonyGravagno** [w2c/ispconfig3_roundcube#111]
Summary: click the mail client icon from ISPConfig, the requested mailbox is not opened, the existing mailbox remains open.

Open a link from the ISPConfig Mailbox account list. The icons have links like this:    
https://my.server:8080/mail/webmailer.php?id=9

On first click, a new tab is opened, there is the correct prompt for the user/password, and login is successful.
Leave that tab open and go back to the ISPConfig tab. Mouseover any other mailbox. The icon does show the correct ID. Click the link. The connection is made, there is a 302 redirect to "webmail" and a 301 from there to "/webmail/". But that just reloads the logged-in page that was already there. I expected that it would open a new tab, or in re-using the existing tab that it would logout of the current mailbox and prompt for the new one.

I'm sorry but this part is not 100% repeatable yet...
Logout of the tab that's in Roundcube. The user/password fields display for Login. Back in ISPconfig, click the icon for another mailbox user. The new user isn't requested to login, the previous logged-in user re-displays.

Let's focus on the first 100% repeatable part, clicking the webmailer.php?id=00 link which does not open a new user. Is the answer here that the user must logout, that per-spec opening another link should not force a new login?

The second part might not be valid. I'll post back if I see it later.

Thanks.

**Comment by thompol** [comment]
All that link from the panel does is take you to the correct Roundcube installation. It is not meant to auto login for a user, pass credentials, or anything. And these plugins are not related to that.

**Comment by TonyGravagno** [comment]
Fair enough. The ID is passed to webmailer.php so I thought it would be used. It's fine if not. Thanks.

**Comment by thompol** [comment]
No, the ID is no determine the correct webmail server, it doesn't pass that to Roundcube.

Some installations have user a@a.com on server1.example.com with webmail on said server, and user b@b.com on server2.example.com with webmail on server2. You can configure the correct hostname for webmail in ISPConfig, and the ID indicates which server should be user for that user.
