### ISSUE TITLE
Soap Error: Forbidden 

### ISSUE THREAD

**Issue by rhassing** [w2c/ispconfig3_roundcube#112]
Hello,

For all the plugins I get an error "Soap Error: Forbidden.

If I check my access_log I see the following:

127.0.0.1 - - [27/Nov/2020:08:44:02 +0100] "POST /remote/index.php HTTP/1.1" 200 534 "-" "PHP-SOAP/7.1.33"
127.0.0.1 - - [27/Nov/2020:08:44:02 +0100] "POST /remote/index.php HTTP/1.1" 200 5198 "-" "PHP-SOAP/7.1.33"
127.0.0.1 - - [27/Nov/2020:08:44:02 +0100] "POST /remote/index.php HTTP/1.1" 200 552 "-" "PHP-SOAP/7.1.33"
127.0.0.1 - - [27/Nov/2020:08:44:02 +0100] "POST /remote/index.php HTTP/1.1" 403 218 "-" "PHP-SOAP/7.1.33"

So it seems it does work 3 times, but the 4th session is forbidden.
I think I can asume Soap is working correctly, my remote access is working as it should, but something is blocking the access.

I checked evasion and added the following to my httpd.conf:
DOSWhitelist 127.0.0.1

Roundcube Webmail 1.2.5

Plugin | Version | License | source
-- | -- | -- | --
filesystem_attachments | 1.0 | GPLv3+ |  
ispconfig3_account | -- |   |  
ispconfig3_autoreply | -- |   |  
ispconfig3_fetchmail | -- |   |  
ispconfig3_filter | -- |   |  
ispconfig3_pass | -- |   |  
ispconfig3_spam | -- |   |  
ispconfig3_wblist | -- |   |  
jqueryui | 1.10.4 | GPLv3+ |  

Best regards,
Rob

**Comment by Churro** [comment]
Hi,

Have you tried disabling mod_evasive entirely (for testing)? I suspect that your IP whitelisting has no effect and since all the requests you listed seem to be issued within the same second, it might just hit `DOSPageInterval`. Other than that, I don't think this issue is actually a bug.

**Comment by rhassing** [comment]
Yes I have tried disabling mod_evasive as well, no luck :-(

**Comment by Churro** [comment]
Since two of 3 requests get a reply where HTTP error code is 200, could it be that you probably didn't tick all the [needed functions](https://github.com/w2c/ispconfig3_roundcube/wiki/Installation#step-2) in ISPConfig?

**Comment by rhassing** [comment]
I ticked almost all the boxes as I expected the same. So all boxes dealing with mail are ticked.

**Comment by rhassing** [comment]
It seemed that mod_evasive was loaded in a seperate conf file :-( 
My bad...
