### ISSUE TITLE
ispconfig3_autoreply - In the Forwarding address field of Roundcube all email addresses are shown

### ISSUE THREAD

**Issue by gscaglia** [w2c/ispconfig3_roundcube#116]
Using the ispconfig3_ autoreply plugin for Roundcube (ISPconfig 3.2.2 on Debian 10 with Roundcube 1.3.16) when the user adds an email address for auto forwarding this is displayed, along with all the others (if any), separated by commas, in the Forwarding address field of Roundcube exactly as happens in the Send copy to field in the mailbox management in the ISPConfig panel.

In the ISPConfig panel this behavior is correct, but in Roundcube it confuses the user, who in order to add a new email address for automatic forwarding must first delete everything written in the Forwarding address field.

First of all I would like to warn the developers to correct this error, which I think affects all those who make the Roundcube webmail with the ISPConfig plugin available to their customers.

And then I ask if there is a quick way to correct this behavior right away (in which file should I act, etc.)

Thanks a lot

**Comment by Churro** [comment]
I agree that the behavior you described was not quite intuitive. Therefore, it was changed with commit b6e37a713d2b524716222c80817e36f436bc44d9.
