### ISSUE TITLE
CC not working anymore with ispconfig 3.2.2

### ISSUE THREAD

**Issue by ketoraire** [w2c/ispconfig3_roundcube#118]
A new field made is entrance in ispconfig 3.2.2

- Forward_in_lda = y or n

So a little modification of the pluging ispconfig3_forward/ispconfig3_forward.php is needed

Is have to add this line: $params['forward_in_lda'] = ($type != 'del' ? 'y' : 'n' );
![image](https://user-images.githubusercontent.com/9216494/108407361-a4bf7580-71f1-11eb-99b1-52673090dff1.png)

And this is working again!

**Comment by Churro** [comment]
Thanks, this was just added with commit bcc95fe920c282a54ed56e16f2af48bf9bf6ebbd
