### ISSUE TITLE
Class 'SoapClient' not found in /path/to/roundcube/plugins/ispconfig3_autoselect/ispconfig3_autoselect.php:24

### ISSUE THREAD

**Issue by S-A-L13** [w2c/ispconfig3_roundcube#125]
Hi,
I just tried to install the ispconfig3 roundcube plugin. Now roundcube has an internal error (It runs before). The Log says this:
`Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'SoapClient' not found in /var/www/clients/client25/web108/web/roundcubemail-1.5.1/plugins/ispconfig3_autoselect/ispconfig3_autoselect.php:24\nStack trace:\n#0 /var/www/clients/client25/web108/web/roundcubemail-1.5.1/program/lib/Roundcube/rcube_plugin_api.php(105): ispconfig3_autoselect->init()\n#1 /var/www/clients/client25/web108/web/roundcubemail-1.5.1/program/include/rcmail.php(153): rcube_plugin_api->init()\n#2 '/var/www/clients/client25/web108/web/roundcubemail-1.5.1/program/include/rcmail.php(86): rcmail->startup()\n#3 /var/www/clients/client25/web108/web/roundcubemail-1.5.1/index.php(43) : rcmail::get_instance()\n#4 {main}\n  thrown in /var/www/clients/client25/web108/web/roundcubemail-1.5.1/plugins/ispconfig3_autoselect/ispconfig3_autoselect.php on line 24'`
If I deactivate the plugins all works normal.
My System:
Roundcube 1.5.1
PHP7.4-fpm
ISPConfig 3.2.7p1

Just tell me, if you need more details or logging.

Thanks and regards
Steffen

**Comment by Churro** [comment]
Hi,
I guess you forgot to install the SOAP client extension for PHP: `apt-get install php7.4-soap`

**Comment by S-A-L13** [comment]
Yep, you're right. That extension was missed. Big thanks to you!
I think it should be mentioned in the requirements part of the Wiki. I would add it, but I'm new to this project and don't know if its welcome if a newbie add content there.

**Comment by Churro** [comment]
Agreed, very good suggestion. Of course your contribution would be very much appreciated but I already added a note about the SOAP extension to the Wiki now. Feel free to edit/adapt it.
