### ISSUE TITLE
Support for postfix "smtpd_tls_auth_only = yes"

### ISSUE THREAD

**Issue by muelli75** [w2c/ispconfig3_roundcube#127]
Support for forced TSL-Authentication would be very useful

Postfix/main.cf
smtpd_tls_auth_only = yes

At this time its not working:
"SMTP Error (250) Authentication is failed"
is given
<img width="958" alt="Bildschirmfoto 2022-06-04 um 16 26 44" src="https://user-images.githubusercontent.com/6082880/172006616-b1e7b5dc-636f-4adf-b809-0bc999113475.png">

**Comment by Churro** [comment]
Hi @muelli75, the error message you are seeing in Roundcube is not related to our plugins.

Most likely you are missing `$config['smtp_server'] = 'tls://localhost';` and/or `$config['smtp_port'] = 587;` in your `config.inc.php`. More information can be found e.g., here:
* https://bobcares.com/blog/roundcube-smtp-error-250-authentication-failed/
* https://www.howtoforge.com/community/threads/postfix-roundcube-tls-problem-after-perfect-server-tutorial.83449/
