### ISSUE TITLE
Autoreply date picker problem

### ISSUE THREAD

**Issue by cepela** [w2c/ispconfig3_roundcube#128]
Cannot select future start date from picker. If set date to future in text and save it, picker show up to set date + one day.
Same problem on two srv. (first Ubuntu 20.04, Apache, PHP 8.2, RC 1.6.1, second Ubuntu Apache, PHP 7.4.33, RC 1.6.0)

![startdate](https://user-images.githubusercontent.com/59801969/234411452-44fd06f0-9608-4f94-aa5b-992c03f158a3.jpg)

![manualstart](https://user-images.githubusercontent.com/59801969/234412109-99673a3e-52f5-4f13-a862-7348cd6de772.jpg)

**Comment by Churro** [comment]
The first screenshot indeed shows a strange condition but I can't reproduce it on my end.

The second screenshot shows correct behavior: The start date can't be behind the end date, so it makes sense to have the start date picker limited to the end date.

**Comment by cepela** [comment]
Looks like i must set end date first and start data as second.
