### ISSUE TITLE
Can not change password

### ISSUE THREAD

**Issue by ykorzikowski** [w2c/ispconfig3_roundcube#129]
Everything else seems working fine, but Pasword change will always tell me `Current Password is incorrect`

- ISPConfig 3.2.8p1
- Roundcube in docker: instrumentisto/roundcube:1.6.0-apache + soap extension

I could not get any useful logs in neither roundcube or ispconfig. 

I am using Keycloak as Auth Provider with roundcube and configured dovecot for this. I do not know if this is interrupting the passwrod change feature.

**Comment by Churro** [comment]
I'm sure this has to do with the use of KeyCloak. The plugin sends a request to ISPConfig and changes the password. If Roundcube / Dovecot is configured with some other authentication mechanism, this plugin cannot take that into account.
