### ISSUE TITLE
Feature Request: Address Book?

### ISSUE THREAD

**Issue by AaronHorn** [w2c/ispconfig3_roundcube#34]
How simple would it be to create a global address book populated from ISPConfig mailboxes?

**Comment by AaronHorn** [comment]
Hi again,

I've been off doing other things for a while now.  I apologise for never getting back in touch.

To elaborate, I think it would be really useful to have some kind of public address book (like in Exchange) which is populated with ISPConfig'ed accounts.  Is this possible?

**Comment by horfic** [comment]
yes this would be possible, but it would only list name and email which is provided in ispconfig, so in roundcube it would be read only, question is also if it should be limited per domain or ispconfig global etc

**Comment by AaronHorn** [comment]
For us, that would work really well since we name everyone properly...

I suspect it should probably be limited by domain or at least by client to fit in with the ISPConfig methodology.  For us it doesn't matter, we only have one domain..

**Comment by horfic** [comment]
well contact us per email and we will send you a quote for this, customized to your needs

**Comment by AaronHorn** [comment]
Thanks :)
