### ISSUE TITLE
Multiple Servers

### ISSUE THREAD

**Issue by ZeroEnna** [w2c/ispconfig3_roundcube#43]
I would like to ask if it is possible to use the support for multiple servers.
my Roundcube now is configured to have this as default host:

mail.%s 

He looks for the server via the DNS A Record mail.example.com (because I use one interface for two servers).

Now, I would like to connect the interface to two different ISPConfig instances. Would be great to somehow make it possible, for example with an if-then-loop or changing the "ISPConfig Address" to 

https://mail.%s:8080/remote/

Thank you in advance.

**Comment by horfic** [comment]
two seperate ispconfig instances or two in a cluster?

two in a cluster is supported. please have a look at the autoselect plugin

**Comment by ZeroEnna** [comment]
Hello,

Two seperate instances. Maybe You Can connect that via the default host Parameter in Roundcube.

Regards

Zero 

----- Ursprüngliche Nachricht -----
Von: "Horst Fickel" <notifications@github.com>
Gesendet: ‎28.‎02.‎2015 09:01
An: "w2c/ispconfig3_roundcube" <ispconfig3_roundcube@noreply.github.com>
Cc: "ZeroEnna" <sascha@schroederswelten.de>
Betreff: Re: [ispconfig3_roundcube] Multiple Servers (#43)

two seperate ispconfig instances or two in a cluster?
two in a cluster is supported. please have a look at the autoselect plugin

**Comment by horfic** [comment]
this is not possible with the current plugins, i would need to rewrite all of them as they are currently using a config file for ispconfig connection. Please contact us per email to get a quote for it
