### ISSUE TITLE
Request of new filter Action feature

### ISSUE THREAD

**Issue by filo** [w2c/ispconfig3_roundcube#44]
Hi,

I would like to ask whether there is the possibility to implement Action: Redirect/Send copy to email if CONDITION.

Tested working sieve rule, but I dont know how to implement the Forward action in Roundcube with ISPConfig3 plugins :-(
if header :regex  ["subject"] [".*word"] {
  redirect "another@email.com";
  stop;
}

I've also created a topic for the ISPConfig:
https://www.howtoforge.com/community/threads/roundcube-filter.67762/

Thanks for your answer

**Comment by horfic** [comment]
well a simply redirect is done by the forwarding plugin, 

before ispconfig was supporting forwarding we implemented our own solution. you can use it for your special things.

Here the last version of forwarding plugin before the change

https://github.com/w2c/ispconfig3_roundcube/blob/2fd562b0afed1d0ff72f96568d1ef1820043e9ea/ispconfig3_forward/ispconfig3_forward.php

**Comment by filo** [comment]
Hi,

I know but its only basic forwarding. I need forwarding based on regex for example in subject like this:
http://s18.postimg.org/dp0lskm7t/Bez_n_zvu.jpg

I have no experience with your code, so its hard to code this feature for me :-(

**Comment by horfic** [comment]
if you got dovecot and sieve port enabled, you can try the roundcube sieve plugin, this provides you with more options.

this plugin suite is currently only supporting ispconfig supported features
