### ISSUE TITLE
ispconfig3_autoselect missing contacts

### ISSUE THREAD

**Issue by ptrj** [w2c/ispconfig3_roundcube#45]
After activated ispconfig3_autoselect plugin I lost all my roundcube settings, like address book contacts, signature etc..
After login in to the Roundcube, plugin create duplicite user in a roundcube database, table users. Row mail_host is by default localhost, but plugin create a new row with mail_host which contains mailhostname

**Comment by horfic** [comment]
yes, ispconfig3_autoselect uses mail server name from ispconfig, thats most of the time the hostname of the mailserver.

This plugin is only for multiple mail server.

**Comment by ptrj** [comment]
thank you :-)
