### ISSUE TITLE
Soap Error: Could not connect to host

### ISSUE THREAD

**Issue by texxasrulez** [w2c/ispconfig3_roundcube#46]
After enabling and configuring the plugins, I get the following alert 'Soap Error: Could not connect to host"

I also have "Broken pipe: [client 192.168.0.1:65277] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function" in my apache error log.

**Comment by ismo-conguairta** [comment]
What is your PHP version?

This should be related to [php-5.6](http://php.net/manual/en/migration56.openssl.php). All encrypted client streams now enable peer verification by default. If you use a self-signed certificate, the peer verification fails. In my ispconfig installation on Debian Jessie I solved with the following steps.

Copy the ISPconfig CA (=CRT for self-signed) to dir */usr/local/share/ca-certificates/*
```shell
# cp /usr/local/ispconfig/interface/ssl/ispserver.crt /usr/local/share/ca-certificates/
# update-ca-certificates
```

Then change the related php.ini file. If you use fcgi for roundcube you have to modify */etc/php5/cgi/php.ini* and add in section **[openssl]** the following line:
```
openssl.cafile=/etc/ssl/certs/ca-certificates.crt
```

Then, restart apache
```shell
# service apache2 restart
```

**Comment by laconic888** [comment]
Hello!
I have a OS: Debian Jessie (8.1)
Roundcube Webmail 1.1.2
ISPConfig 3.0.5.4p8
PHP 5.6.9-0+deb8u1
SQL 5.5.44-0

*Config.inc.php file:*

    <?php
    $rcmail_config['identity_limit'] = false;
    $rcmail_config['remote_soap_user'] = 'remoteuser_ispconfig';
    $rcmail_config['remote_soap_pass'] = 'remoteusers_passwrd';
    $rcmail_config['soap_url'] = 'https://192.168.0.101:8080/remote/';
    ?>

And of course I've done:

    # cp /usr/local/ispconfig/interface/ssl/ispserver.crt /usr/local/share/ca-certificates/
    # update-ca-certificates

    in file /etc/php5/cgi/php.ini changed section [openssl] to:
    openssl.cafile=/etc/ssl/certs/ca-certificates.crt

but still: **Soap Error: Could not connect to host**

### Have you any more ideas about It? ###

**Comment by ismo-conguairta** [comment]
@laconic888, are you sure that PHP runs in CGI/FASTCGI mode? You have to change the correct php.ini file depending on the way you run PHP. If you're using FASTCGI you have to change /etc/php5/cgi/php.ini, if you're using FPM you have to change /etc/php5/fpm/php.ini, while if you're using APACHE-MODULE you have to change /etc/php5/apache2/php.ini.

To know what mode you're using, you can check the first lines in phpinfo (take a look at screenshot).
![screenshot-phpinfo](https://cloud.githubusercontent.com/assets/3636147/9170558/355011ac-3f64-11e5-876e-48238a5337e2.png)

**Comment by laconic888** [comment]
@ismo-conguairta As you can see, CGI/FASTCGI mode active :(

![screenshot](https://cloud.githubusercontent.com/assets/13721385/9174891/29e477e4-3f9c-11e5-997a-c357a4356276.png)

**Comment by horfic** [comment]
do you got mod_security installed?

**Comment by laconic888** [comment]
@horfic **THANK YOU!**
I haven't installed mod_security. Now I load It and everything works fine!
Many thanks to you! :+1:

**Comment by MirekK0** [comment]
some error ... i change PHP version for roundcube website from 5.6.0 to 5.5.15 and it WORKS .... :-)

**Comment by ismo-conguairta** [comment]
@horfic, @laconic888, Just to point out that I have got no need to install/enable mod_security. It works as is, excepted for the steps mentioned before.

**Comment by jrdiver** [comment]
I have ISPconfig  and Roundcube (1.1.2) setup on a vps running Ubuntu 15.04 and PHP 5.6.4-4ubuntu6.2.  I followed the above steps and I am still getting the "Soap Error: Could not connect to host" Problem.  ISPconfig is set to use Fast-CGI, and i have a self signed certificate.  From what i can see my setup on the php side is about the same as @laconic888 above me.  Whats the best way to fix this problem?

![php](https://cloud.githubusercontent.com/assets/12983591/9486642/8e3cc4ea-4b8f-11e5-801e-a9be18136924.jpg)

**Comment by ismo-conguairta** [comment]
The parameter *$rcmail_config['soap_url']* should be configured with the server name that the SSL certificate was generated for.

Try this to verify the hostname in field CN:
```shell
# openssl x509 -in /usr/local/share/ca-certificates/ispserver.crt -text -noout | grep Subject:
```

Output example:
```shell
Subject: C=XX, ST=XXXX, L=XXXX, O=XXXXX Ltd., CN=mydomain.net/emailAddress=sysadmin@mydomain.net
```

Then you have to change the configuration file:
```php
$rcmail_config['soap_url']='https://mydomain.net:8080/remote/';
```

**Comment by jrdiver** [comment]
My certificate had the www. in it, adding that removed the error

Thanks!

**Comment by Cypouz** [comment]
Hi there!

Same alert after updating my install (Debian 8, ISPConfig 3.1)... I have also tried the certificate tricks without success but I don't think it's needed since certification validation was disabled (https://github.com/w2c/ispconfig3_roundcube/commit/4f1ba82b3ea38a570258ef4d7dba74b5330e511d).

Can you help me?
