### ISSUE TITLE
ISPConfig 3.0.5.4 + roundcube 1.1.3.

### ISSUE THREAD

**Issue by makmary170** [w2c/ispconfig3_roundcube#51]
Hello! Is this plagin supports new version of roundcube (1.1.3)?

**Comment by horfic** [comment]
Not yet, will be fixed this week

**Comment by makmary170** [comment]
Ok. Thanks

**Comment by makmary170** [comment]
Have you news about this issue, pls?

**Comment by horfic** [comment]
currently fixing it, will be released in few hours

ps: thanks for the reminder^^

**Comment by makmary170** [comment]
=)

**Comment by Churro** [comment]
Should now be fixed with the most recent commit :)
