### ISSUE TITLE
Ispconfig3 roundcube with elastic skin

### ISSUE THREAD

**Issue by sgregori** [w2c/ispconfig3_roundcube#81]
Hi friends,

Today i deployed a new installation of roundcube with master branch release, and it has a new skin named elastic.

I symlinked the classic and larry skin subfolder at plugins, it doesnt crash but is not fully working.

Before starting to code, i searched for any version of this plugin adapted to recent releases of roundcube but found nothing.

Is this repository still alive ? Someone are working on it ?

Thanks

**Comment by Churro** [comment]
Hi,

The elastic skin is still in development. So far no steps for integration have been made as it would be quite cumbersome to continuously having to adapt the code to ongoing changes in Roundcube. If you are going to work on it, your pull request will be very welcome :-)

**Comment by sgregori** [comment]
Thank you!

At the moment, we can change to classic skin (make some changes) and get back to elastic, but i will try to adapt the plugin to the skin or the skin to the plugin ( i'm not sure yet ).

Regards.

**Comment by iopsthecloud** [comment]
Hi @sgregori

Did you find a way to have the elastic skin work ? I did the symlink too but it's completely useless :(

Regards.

**Comment by Churro** [comment]
Hi,

We are already working on it. Stay tuned! :-)

**Comment by kosli** [comment]
@churro just upgraded my roundcoube to the newly release 1.4.0 and after upgrading the ispconfig plugins too, everything works like a charm. great work, thanks!
