### ISSUE TITLE
Not showing up on new Ubuntu 18.04 install

### ISSUE THREAD

**Issue by jfreak53** [w2c/ispconfig3_roundcube#83]
Fresh install on Ubuntu 18.04 and it's not showing up under Settings. Nothing in error logs either. PHP 7.2. Installed the same way I did on another two servers with 16.04, no problems there.

http://cdn.microtronix-tech.com/imgs/Screenshot_at_2018-09-13_16-07-29.png

Roundcube Webmail 1.3.6
ISPConfig Version 3.1.13

**Comment by Churro** [comment]
Please try the newest version. We have changed the way the plugin attaches to the Roundcube settings.
