### ISSUE TITLE
Adding new identity fails when identity_limit is set to true

### ISSUE THREAD

**Issue by MachineITSvcs** [w2c/ispconfig3_roundcube#86]
Thank you for these plugins! I am having an issue with the account plugin though. When I have the identity_limit set to true, the existing identities display with the dropdown as they should, but when I attempt to add a new identity, the page loads indefinitely. I was able to gather the following from the roundcube logs. Maybe you could point me in the right direction to fixing whatever the issue may be. Thank you again.

The log stack trace is as follows:
#0 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(440): ispconfig3_account->template_object_identityform(Array)
#1 /usr/share/roundcube/program/include/rcmail_output_html.php(1208): rcube_plugin_api->exec_hook('template_object...', Array)
#2 [internal function]: rcmail_output_html->xml_command(Array)
#3 /usr/share/roundcube/program/include/rcmail_output_html.php(1013): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...')
#4 /usr/share/roundcube/program/include/rcmail_output_html.php(634): rcmail_output_html->parse_xml('<roundcube:obje...')
#5 /usr/share/roundcube/program/include/rcmail_output_html.php(488): rcmail_output_html->parse('identityedit', false)
#6 /usr/share/roundcube/program/steps/settings/edit_identity.inc(63): rcmail_output_html->send('identityedit')
#7 /usr/share/roundcube/index.php(303): include_once('/usr/share in /usr/share/roundcube/plugins/ispconfig3_account/ispconfig3_account.php on line 91

**Comment by Churro** [comment]
Hi,

That was indeed a bug, fixed with commit 977d2c0. The SOAP object managing the connection to ISPConfig was only available when editing an identity but not when adding a new one.

Also, the account plugin only worked with one existing identity but didn't replace the text input field for additional identities. This has also been fixed by modifying the used RegEx.
