### ISSUE TITLE
Plugins wont work when using 'Alternative Login'

### ISSUE THREAD

**Issue by RayMatrix** [w2c/ispconfig3_roundcube#88]
Hey,

we are using the alternativ login - with emailadress.
So the Plugins wont work in roundcube.

We had find these lines:
$mail_user = $this->soap->mail_user_get($session_id, array('**login**' => $this->rcmail->user->data['username']));

And changed them to:
$mail_user = $this->soap->mail_user_get($session_id, array('**email**' => $this->rcmail->user->data['username']));

Maybe there is a way the plugins check the login and email var

**Comment by nicrame** [comment]
I believe that using email address is the default way in ISPConfig, so using Roundcube forces to use full email address. So it should work without changing anything (in my case it works out of the box).

**Comment by RayMatrix** [comment]
I dont think so.
There is a function at the adminpanel at: System => Main Config => Mail => Allow custom login name
If you allow this, the plugins wont work.

**Comment by nicrame** [comment]
Well, yes, but this isn't default option (by default it is unchecked). When You check it, then You allow using non standard email logins (like myemail instead of myemail@domain.com). But it may be true, that this plugin do not work correctly with this (but i didn't look inside).
What file did You changed?

**Comment by RayMatrix** [comment]
We changed these files:

ispconfig3_account/ispconfig3_account.php
ispconfig3_autoreply/ispconfig3_autoreply.php
ispconfig3_autoselect/ispconfig3_autoselect.php
ispconfig3_fetchmail/ispconfig3_fetchmail.php
ispconfig3_filter/ispconfig3_filter.php
ispconfig3_forward/ispconfig3_forward.php
ispconfig3_spam/ispconfig3_spam.php
ispconfig3_wblist/ispconfig3_wblist.php

**Comment by StrathCole** [comment]
When you change the "allow custom login" in ISPConfig, you can use BOTH, login and email address to login via IMAP. So roundcube can be used either with email or with login. That causes the confusion.
`$mail_user = $this->soap->mail_user_get($session_id, array('login' => $this->rcmail->user->data['username']));`
has to be
`
$mail_user = $this->soap->mail_user_get($session_id, array('login' => $this->rcmail->user->data['username']));
if(!isset($mail_user[0]) || !isset($mail_user[0]['sys_userid'])) {
                        $mail_user = $this->soap->mail_user_get($session_id, array('email' => $this->rcmail->user->data['username']));
                        }

`
or something similar to address this.

**Comment by helmo** [comment]
I came to almost the same patch before finding this issue :( ... Lets make a pull request of this to solve this for any future user. See #104
