### ISSUE TITLE
Missing Information in the Installation

### ISSUE THREAD

**Issue by 5ll** [w2c/ispconfig3_roundcube#89]
The Install-Howto in the Wiki is missing an information:

You DO need to tick "remote access" also to be able to use the plugins.

I'm using the latest ISPconfig as well as the latest Roundcube available in debian. Server is an up-to-date debian 9.

**Comment by Churro** [comment]
We updated the install howto with a small note: https://github.com/w2c/ispconfig3_roundcube/wiki/Installation
