### ISSUE TITLE
Provide option for custom sieve rules in Roundcube

### ISSUE THREAD

**Issue by Sanookmakmak** [w2c/ispconfig3_roundcube#92]
![custom_ruleset](https://user-images.githubusercontent.com/24833757/56025706-f1db8200-5d12-11e9-8fb5-cc502825e3c0.png)

**Comment by Churro** [comment]
ISPconfig provides support for Sieve rules through the Dovecot service. Roundcube already includes a plugin called [managesieve](https://github.com/roundcube/roundcubemail/tree/master/plugins/managesieve) that you can enable in order to define Sieve rules.
