### ISSUE TITLE
Not working with roundcube 1.2.3 (debian stable package) and ispconfig 3.1.13

### ISSUE THREAD

**Issue by Harvie** [w2c/ispconfig3_roundcube#93]
I've have roundcube 1.2.3 (package from debian stable) and ispconfig 3.1.13
Tried to install git master of ispc roundcube plugins.

**I've followed "Requirements", "Instalation" and "Troubleshooting" pages in wiki, without any success.**

No sign of plugins working, no plugin-related error message. I can login if i manualy enter server, otherwise, when i leave server inputbox blank i get "Invalid Server Name". But even when i manage to login, i don not see "accounts" section in my settings.

I don't really need to get most of the plugins working, for me only important plugins are autoselect and maybe password changer. Other plugins are nice to have, but certainly not crucial...

Any ideas?

**Comment by alpianon** [comment]
If you are using Debian, did you installed ISPConfig SSL certificate into the Debian certificate store, and then modified php.in accordingly?

https://www.howtoforge.com/tutorial/roundcube-installation-on-debian-8-jessie/
(it works also on newer version of Debian, you just have to change php config dir)

**Comment by Harvie** [comment]
It's been some time since i've tried that. However i believe that i've followed instructions written in wiki:
https://github.com/w2c/ispconfig3_roundcube/wiki/Installation

These do not contain such step.

**Comment by alpianon** [comment]
I see, but I remember that installing the certificate was necessary in order to make it work. Probably the wiki should be updated

**Comment by VojtechMyslivec** [comment]
Hello, was that resolved? I encountered similar issue: ISPC plugins does not work after upgrade to Debian Buster, where PHP 7.3 is the default php version.

When I switch to PHP version 7.0, plugins start to work again. So it seems plugins are not compatible with PHP 7.2 or later (I haven't tried 7.1 yet).

**Comment by aartsr** [comment]
also, the wiki still hasn't been updated... it would be good to have either the contents updated or replaced with a link to the instructions (including ssl cert step) at howtoforge

**Comment by ladowny** [comment]
It does not work for me either with Roundcube 1.3.15 (packaged by Debian ) and ISPConfig 3.1 on Debian 10 
This is most probably because of mcrypt package which is obsolete and has been removed from Php 7.1 https://www.php.net/manual/de/migration71.deprecated.php 
It can still be installed with pecl,  however it is based on libmcrypt that hasn’t been developped since 2007, so I am a bit reluctant to install it.

**Comment by ladowny** [comment]
I got it working with latest Roundcube Webmail 1.4.8 so looks like the issue was with older Roundcube versions

**Comment by VojtechMyslivec** [comment]
I can confirm these plugins works for me in PHP 7.3 on Debian 10.5, Roundcube 1.4.8 (from debian-backports) and ISPConfig 3.11.15 :heavy_check_mark:

**Comment by Churro** [comment]
> It does not work for me either with Roundcube 1.3.15 (packaged by Debian ) and ISPConfig 3.1 on Debian 10
> This is most probably because of mcrypt package which is obsolete and has been removed from Php 7.1 https://www.php.net/manual/de/migration71.deprecated.php
> It can still be installed with pecl, however it is based on libmcrypt that hasn’t been developped since 2007, so I am a bit reluctant to install it.

The plugins work well with Roundcube 1.3.15 (also in buster) as well as 1.4 (also in buster-backports). However, there is nothing related to mcrypt in our code, so I suspect your problem was more likely related to the `SoapClient` (package `php-soap`) not being installed.

**Comment by Ark74** [comment]
Hello when enabling the modules on a nginx + php7.4 + roundcube 1.4.3 on focal seems to send 500 internal error.
No soap errors so far, any advice new comments or advice on this kind of setup?

Regards.
