### ISSUE TITLE
roundcube 1.4 compatibility?

### ISSUE THREAD

**Issue by aartsr** [w2c/ispconfig3_roundcube#96]
Hi guys,

been succesfully using several of your plugins for quite some time now. Thanks for that! 

Now for the current 'issue': recently Roundcube 1.4 was released with some big changes (elastic/less/etc) and I am wondering if any problems are to be expected with the plugins if I would upgrade from roundcube 1.3.10 to 1.4.0?

Thanks a bunch again!

[RC 1.4 changelog](https://github.com/roundcube/roundcubemail/releases/tag/1.4.0)

**Comment by kosli** [comment]
I am using the plugin versions from git repo together with the 1.4.0. release and haven't had any issues yet.

**Comment by aartsr** [comment]
thanx  @kosli for the updat..., I think I last updated the plugins in 2017 so I'll update those first and then try the roundcube upgrade later this weekend :)

By the way, how do you like RC 1.4.x? :)

**Comment by kosli** [comment]
RC 1.4: great! i love it! 
.... and realized only lately that there is/was always a IMAP ACL plugin to configure the folder sharing :-)

**Comment by Ark74** [comment]
Hello guys!
I'm testing roundcube | 1.4.3+dfsg.1-1 from focal, along with php7.4 and getting 500 errors when enabling the plugins, @Churro may this be a known issue or could it be a misconfiguration from my part.

Happy 2021!

**Comment by Churro** [comment]
> I'm testing roundcube | 1.4.3+dfsg.1-1 from focal, along with php7.4 and getting 500 errors when enabling the plugins, @Churro may this be a known issue or could it be a misconfiguration from my part.

No known issue at least. For more details, please check the log files of your webserver stating the reason for 500 errors.
