### ISSUE TITLE
soap connection error with sectigo cert

### ISSUE THREAD

**Issue by aartsr** [w2c/ispconfig3_roundcube#98]
Just updated to the latest versions of the plugins and - not sure why and haven't really investigated - but I had to set soap_validate_cert option to false (I didnt have this line in my config file before) even though I'm not using a self signed cert (sectigo positivessl). Just giving everybody who runs into the same thing a heads up I guess.

**Comment by Churro** [comment]
Thanks for the heads up. In previous versions, the cert not was validated by default as most ISPConfig setups used generated self-signed certs. 

If your CA-issued cert cannot be verified, it is likely that your local PHP cannot access a list of trusted CAs. Therefore, you have to set `curl.cainfo` in `php.ini` to a valid path of trusted certificates, see https://wpquark.com/kb/misc/server-management/fixing-curl-ssl-connection-issue-php-ini/

I've now updated the [Troubleshooting FAQ](https://github.com/w2c/ispconfig3_roundcube/wiki/Troubleshooting---FAQ) to cover this issue.
